wildfly:
    image: wyvie/wildfly-9-postgre
    ports:
        - "8081:8080"
        - "9990:9990"
    volumes:
        - ./target:/opt/jboss/wildfly/standalone/deployments/
    links:
        - postgres:postgres
postgres:
    image: postgres
    environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres.12qwaszx'